spring:
  datasource:
    url: jdbc:clickhouse://localhost:8123/default
    username: root
    password: 123456
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
canal:
  clickhouse:
    configuration:
      instance: canalClickhouseExample
      filter: canal_client_example.t_user
      show-entry-log: false
      show-event-log: true
    enabled: true
    consumer-config-map:
      canal_client_example:
        t_user:
          column-map:
            version: version1
          default-values:
            deleted: 0
          exclude-columns: status,test